questao_10/config/routes.rb
Rails.application.routes.draw do
  resources :fish
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

questao_10/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

questao_10/app/models/fish.rb
class Fish < ApplicationRecord
  validates_presence_of :name
end

questao_10/app/models/shark.rb
class Shark < Fish
  validates_presence_of :color

  def self.findByColor(color)
    raise "wrong type: string required" unless color.is_a?(String)
    Shark.where(color: color)
  end
end

questao_10/app/models/tuna.rb
class Tuna < Fish
  validates_presence_of :origin

  def self.findByOrigin(origin)
    raise "wrong type: string required" unless origin.is_a?(String)
    Tuna.where(origin: origin)
  end
end

questao_10/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

questao_10/app/controllers/fish_controller.rb
class FishController < ApplicationController
  before_action :set_fish, only: [:show, :edit, :update, :destroy]

  # GET /fish
  # GET /fish.json
  def index
    @fish = Fish.all
  end

  # GET /fish/1
  # GET /fish/1.json
  def show
  end

  # GET /fish/new
  def new
    @fish = Fish.new
  end

  # GET /fish/1/edit
  def edit
  end

  # POST /fish
  # POST /fish.json
  def create
    @fish = Fish.new(fish_params)

    respond_to do |format|
      if @fish.save
        format.html { redirect_to @fish, notice: 'Fish was successfully created.' }
        format.json { render :show, status: :created, location: @fish }
      else
        format.html { render :new }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fish/1
  # PATCH/PUT /fish/1.json
  def update
    respond_to do |format|
      if @fish.update(fish_params)
        format.html { redirect_to @fish, notice: 'Fish was successfully updated.' }
        format.json { render :show, status: :ok, location: @fish }
      else
        format.html { render :edit }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fish/1
  # DELETE /fish/1.json
  def destroy
    @fish.destroy
    respond_to do |format|
      format.html { redirect_to fish_index_url, notice: 'Fish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fish
      @fish = Fish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fish_params
      params.require(:fish).permit(:name, :origin, :color)
    end
end

questao_10/app/helpers/application_helper.rb
module ApplicationHelper
end

questao_10/app/helpers/fish_helper.rb
module FishHelper
end

questao_10/app/views/fish/_form.html.erb
<%= form_for(fish) do |f| %>
  <% if fish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fish.errors.count, "error") %> prohibited this fish from being saved:</h2>

      <ul>
      <% fish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :origin %>
    <%= f.text_field :origin %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

questao_10/app/views/fish/edit.html.erb
<h1>Editing Fish</h1>

<%= render 'form', fish: @fish %>

<%= link_to 'Show', @fish %> |
<%= link_to 'Back', fish_index_path %>

questao_10/app/views/fish/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fish</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Origin</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fish.each do |fish| %>
      <tr>
        <td><%= fish.name %></td>
        <td><%= fish.origin %></td>
        <td><%= fish.color %></td>
        <td><%= link_to 'Show', fish %></td>
        <td><%= link_to 'Edit', edit_fish_path(fish) %></td>
        <td><%= link_to 'Destroy', fish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fish', new_fish_path %>

questao_10/app/views/fish/new.html.erb
<h1>New Fish</h1>

<%= render 'form', fish: @fish %>

<%= link_to 'Back', fish_index_path %>

questao_10/app/views/fish/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fish.name %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @fish.origin %>
</p>

<p>
  <strong>Color:</strong>
  <%= @fish.color %>
</p>

<%= link_to 'Edit', edit_fish_path(@fish) %> |
<%= link_to 'Back', fish_index_path %>

questao_10/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Questao10</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>